// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqG_2tbOH__CHOd3lFC8sVVe6ZKlTlEvk',
    appId: '1:223397251529:web:2772a00f61fb8d97210018',
    messagingSenderId: '223397251529',
    projectId: 'seam-flutter',
    authDomain: 'seam-flutter.firebaseapp.com',
    storageBucket: 'seam-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8Ch9uXzbk6f8QrCWhkPyh7qYYfISO_P0',
    appId: '1:223397251529:android:6267e71acfc00316210018',
    messagingSenderId: '223397251529',
    projectId: 'seam-flutter',
    storageBucket: 'seam-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9ElODRaalKv8fp3TIcdjcJJG1M_uLDbM',
    appId: '1:223397251529:ios:f6ecd46bfaa9fc06210018',
    messagingSenderId: '223397251529',
    projectId: 'seam-flutter',
    storageBucket: 'seam-flutter.appspot.com',
    iosBundleId: 'com.example.seamFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqG_2tbOH__CHOd3lFC8sVVe6ZKlTlEvk',
    appId: '1:223397251529:web:cec1bc0ea2dd6800210018',
    messagingSenderId: '223397251529',
    projectId: 'seam-flutter',
    authDomain: 'seam-flutter.firebaseapp.com',
    storageBucket: 'seam-flutter.appspot.com',
  );
}
